language: node_js
node_js:
  - "12"
branches:
  only:
    - source

cache:
  directories:
    - node_modules

install: npm install

before_script:
  - git config --global user.name "epona"
  - git config --global user.email "490472721@qq.com"
  - sed -i "s/GITHUB_API_KEY/${GITHUB_API_KEY}/" _config.yml

script: npm run build
