theme: minima

author: Epona
email: datouhaoruijie@gmail.com

minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    twitter: kappelong
    github:  SimuraEpona
    rss: rss

disqus:
  shortname: blog-efievddr6w

show_excerpts: true
title: 彩虹马厩
description: There's nothing wrong with having a little fun!
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: "_posts" # 一个空的字符串代表项目中所有的文件
    values:
      comments: true
      layout: "post"
